name: Java CI with Maven

on:
  pull_request:
    branches: ["main"]

permissions:
  pull-requests: write
  contents: write

jobs:
  
  build:    

    runs-on: ubuntu-latest

    env:
      PIPELINE_FAIL_FLAG: ${{vars.PIPELINE_FAIL_FLAG}}

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: maven

      - name: Build with Maven
        run: mvn clean install

      - name: Get app version
        run: |
          echo "APP_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

      - name: Add coverage to PR comment
        id: jacoco
        uses: madrapps/jacoco-report@v1.7.1
        with:
          paths: |
            ${{ github.workspace }}/**/target/site/jacoco/jacoco.xml,
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 70
          min-coverage-changed-files: 80
          title: Code Coverage
          update-comment: true
      
      - name: Generate JaCoCo Badge
        uses: cicirello/jacoco-badge-generator@v2
        with:
          generate-coverage-badge: true
          generate-branches-badge: true
          coverage-badge-filename: jacoco.svg
          branches-badge-filename: branches.svg
          jacoco-csv-file: target/site/jacoco/jacoco.csv
    
      - name: Commit and push the badge (if it changed)
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: 'Commit coverage badge'
          committer_name: GitHub Actions
          add: '*.svg'
          push: origin HEAD:${{ github.head_ref }}
    
      - name: Upload JaCoCo coverage report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco/
          
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/pipeline-test-app:${{ env.APP_VERSION }}
